### ISSUE TITLE
Hardcoded S3 path may be preferred to env vars

### ISSUE THREAD

**Issue by jake-picwell** [c4gnv/business-portal-cache-lambda#1]
I used environment variables because it made it easier to push something deployable, but for something like this it may be preferable to have hardcoded values for easy reference.

**Comment by jamessmell** [comment]
@Bjorn248 can you review this and let me know if it's still relevant or whether we can close it?

**Comment by Bjorn248** [comment]
@jamessmell this project is abandoned as far as I can tell, safe to close.

**Comment by jamessmell** [comment]
Closing
